  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.3.5)

2024-10-29T11:51:03.158-05:00  INFO 19944 --- [kv-demo] [           main] com.example.kv_demo.KvDemoApplication    : Starting KvDemoApplication using Java 17.0.3 with PID 19944 (C:\Users\ajoubert\OneDrive - Microsoft\Desktop\kv-demo\target\classes started by ajoubert in C:\Users\ajoubert\OneDrive - Microsoft\Desktop\kv-demo)
2024-10-29T11:51:03.159-05:00  INFO 19944 --- [kv-demo] [           main] com.example.kv_demo.KvDemoApplication    : No active profile set, falling back to 1 default profile: "default"
2024-10-29T11:51:04.042-05:00  INFO 19944 --- [kv-demo] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-10-29T11:51:04.068-05:00  INFO 19944 --- [kv-demo] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 15 ms. Found 0 JPA repository interfaces.
2024-10-29T11:51:05.158-05:00  INFO 19944 --- [kv-demo] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2024-10-29T11:51:05.192-05:00  INFO 19944 --- [kv-demo] [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-10-29T11:51:05.193-05:00  INFO 19944 --- [kv-demo] [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.31]
2024-10-29T11:51:05.349-05:00  INFO 19944 --- [kv-demo] [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-10-29T11:51:05.349-05:00  INFO 19944 --- [kv-demo] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2141 ms
2024-10-29T11:51:05.573-05:00  INFO 19944 --- [kv-demo] [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2024-10-29T11:51:05.827-05:00  INFO 19944 --- [kv-demo] [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection conn0: url=jdbc:h2:mem:92242d98-6755-46d6-86ad-b215c9886e5e user=SA
2024-10-29T11:51:05.827-05:00  INFO 19944 --- [kv-demo] [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2024-10-29T11:51:05.879-05:00  INFO 19944 --- [kv-demo] [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2024-10-29T11:51:05.987-05:00  INFO 19944 --- [kv-demo] [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.5.3.Final
2024-10-29T11:51:06.042-05:00  INFO 19944 --- [kv-demo] [           main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
2024-10-29T11:51:06.451-05:00  INFO 19944 --- [kv-demo] [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2024-10-29T11:51:06.959-05:00  INFO 19944 --- [kv-demo] [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
2024-10-29T11:51:06.968-05:00  INFO 19944 --- [kv-demo] [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2024-10-29T11:51:07.258-05:00  INFO 19944 --- [kv-demo] [           main] c.a.c.h.n.implementation.NettyUtility    : {"az.sdk.message":"The following Netty versions were found on the classpath and have a mismatch with the versions used by azure-core-http-netty. If your application runs without issue this message can be ignored, otherwise please align the Netty versions used in your application. For more information, see https://aka.ms/azsdk/java/dependency/troubleshoot.","azure-netty-version":"4.1.110.Final","azure-netty-native-version":"2.0.65.Final","classpath-netty-version-io.netty:netty-common":"4.1.114.Final","classpath-netty-version-io.netty:netty-handler":"4.1.114.Final","classpath-netty-version-io.netty:netty-handler-proxy":"4.1.114.Final","classpath-netty-version-io.netty:netty-buffer":"4.1.114.Final","classpath-netty-version-io.netty:netty-codec":"4.1.114.Final","classpath-netty-version-io.netty:netty-codec-http":"4.1.114.Final","classpath-netty-version-io.netty:netty-codec-http2":"4.1.114.Final","classpath-netty-version-io.netty:netty-transport-native-unix-common":"4.1.114.Final","classpath-netty-version-io.netty:netty-transport-native-epoll":"4.1.114.Final","classpath-netty-version-io.netty:netty-transport-native-kqueue":"4.1.114.Final","classpath-native-netty-version-io.netty:netty-tcnative-boringssl-static":"2.0.66.Final"}
2024-10-29T11:51:07.525-05:00  WARN 19944 --- [kv-demo] [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2024-10-29T11:51:07.949-05:00  INFO 19944 --- [kv-demo] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path '/'
2024-10-29T11:51:07.964-05:00  INFO 19944 --- [kv-demo] [           main] com.example.kv_demo.KvDemoApplication    : Started KvDemoApplication in 5.735 seconds (process running for 6.292)
2024-10-29T11:51:09.268-05:00  INFO 19944 --- [kv-demo] [           main] c.azure.identity.ChainedTokenCredential  : Azure Identity => Attempted credential EnvironmentCredential is unavailable.
2024-10-29T11:51:09.268-05:00  INFO 19944 --- [kv-demo] [           main] c.azure.identity.ChainedTokenCredential  : Azure Identity => Attempted credential WorkloadIdentityCredential is unavailable.
2024-10-29T11:51:09.355-05:00  WARN 19944 --- [kv-demo] [  az-identity-1] c.m.a.m.ConfidentialClientApplication    : [Correlation ID: a07ffcbf-005f-405b-a9dd-63ff369b951a] Execution of class com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier failed: java.util.concurrent.ExecutionException: com.azure.identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established, Network is unreachable: no further information.
2024-10-29T11:51:09.356-05:00  INFO 19944 --- [kv-demo] [           main] c.azure.identity.ChainedTokenCredential  : Azure Identity => Attempted credential ManagedIdentityCredential is unavailable.
2024-10-29T11:51:09.362-05:00  INFO 19944 --- [kv-demo] [           main] c.azure.identity.ChainedTokenCredential  : Azure Identity => Attempted credential SharedTokenCacheCredential is unavailable.
2024-10-29T11:51:09.367-05:00  INFO 19944 --- [kv-demo] [           main] c.azure.identity.ChainedTokenCredential  : Azure Identity => Attempted credential IntelliJCredential is unavailable.
2024-10-29T11:51:12.239-05:00  INFO 19944 --- [kv-demo] [           main] c.azure.identity.ChainedTokenCredential  : Azure Identity => Attempted credential AzureCliCredential returns a token
2024-10-29T11:51:12.381-05:00  INFO 19944 --- [kv-demo] [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-10-29T11:51:12.399-05:00 ERROR 19944 --- [kv-demo] [           main] o.s.boot.SpringApplication               : Application run failed

com.azure.core.exception.ResourceNotFoundException: Status code 404, "{"error":{"code":"SecretNotFound","message":"A secret with (name/id) h2url was not found in this key vault. If you recently deleted this secret you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182"}}"
        at com.azure.security.keyvault.secrets.SecretAsyncClient.mapGetSecretException(SecretAsyncClient.java:428) ~[azure-security-keyvault-secrets-4.8.7.jar:4.8.7]
        at com.azure.security.keyvault.secrets.SecretClient.callWithMappedException(SecretClient.java:1027) ~[azure-security-keyvault-secrets-4.8.7.jar:4.8.7]
        at com.azure.security.keyvault.secrets.SecretClient.getSecretWithResponse(SecretClient.java:359) ~[azure-security-keyvault-secrets-4.8.7.jar:4.8.7]
        at com.azure.security.keyvault.secrets.SecretClient.getSecret(SecretClient.java:296) ~[azure-security-keyvault-secrets-4.8.7.jar:4.8.7]  
        at com.example.kv_demo.KvDemoApplication.run(KvDemoApplication.java:24) ~[classes/:na]
        at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:790) ~[spring-boot-3.3.5.jar:3.3.5]
        at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83) ~[spring-core-6.1.14.jar:6.1.14]   
        at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60) ~[spring-core-6.1.14.jar:6.1.14]
        at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88) ~[spring-core-6.1.14.jar:6.1.14]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-3.3.5.jar:3.3.5]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789) ~[spring-boot-3.3.5.jar:3.3.5]
        at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:774) ~[spring-boot-3.3.5.jar:3.3.5]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774) ~[spring-boot-3.3.5.jar:3.3.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:342) ~[spring-boot-3.3.5.jar:3.3.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.5.jar:3.3.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.5.jar:3.3.5]
        at com.example.kv_demo.KvDemoApplication.main(KvDemoApplication.java:19) ~[classes/:na]

2024-10-29T11:51:12.720-05:00  INFO 19944 --- [kv-demo] [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2024-10-29T11:51:12.722-05:00  INFO 19944 --- [kv-demo] [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-10-29T11:51:12.722-05:00  INFO 19944 --- [kv-demo] [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.355 s
[INFO] Finished at: 2024-10-29T11:51:13-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.3.5:run (default-cli) on project kv-demo: Process terminated with exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException